window.addEventListener('load',function(){setTimeout(function(){atlasBindDraftAutosave();var raw=localStorage.getItem(atlasProjectStorageKey());if(raw){try{var d=JSON.parse(raw);atlasSetWorkspaceStage(d.stage||'input',{noSave:true,coach:'저장된 프로젝트가 있습니다. 불러오기 버튼을 누르면 이어서 작업할 수 있습니다.'});}catch(e){atlasSetWorkspaceStage('input',{noSave:true});}}else atlasSetWorkspaceStage('input',{noSave:true});},350);});
/* Atlas Final Integrated Layer */
var ATLAS_PLATFORM='kmong';
function atlasPlatformChanged(v){ATLAS_PLATFORM=v||'kmong';if(APP&&APP.ebook){renderKmongListing(APP.ebook);renderAtlasQuality();}atlasSaveDraft(false);showToast('success','판매 플랫폼이 변경되었습니다.');}
function atlasTextLen(v){return String(v||'').replace(/<[^>]*>/g,'').trim().length;}
function atlasClamp(n){return Math.max(0,Math.min(100,Math.round(n)));}
function atlasQualityScores(e){
 e=e||{};var ch=e.chapters||[],sales=e.sales||{};
 var body=ch.reduce(function(a,c){return a+atlasTextLen(c.content);},0);
 var completeness=atlasClamp(45+ch.length*5+(e.intro?5:0)+(e.conclusion?5:0)+(e.appendices&&e.appendices.length?5:0));
 var readability=atlasClamp(88-(ch.some(function(c){return atlasTextLen(c.content)>7000;})?7:0)+(ch.every(function(c){return c.keyPoints&&c.actionItems;})?6:0));
 var salesScore=atlasClamp(55+(sales.hook?10:0)+(sales.pains&&sales.pains.length>=3?8:0)+(sales.learnings&&sales.learnings.length>=3?8:0)+(sales.faqs&&sales.faqs.length>=3?8:0)+(sales.finalPush?6:0));
 var policy=100;var txt=JSON.stringify({title:e.title,subtitle:e.subtitle,sales:sales});if(/100\s*%|무조건|수익\s*보장|매출\s*보장|자동\s*수익|월\s*\d[\d,]*\s*(?:만|억|천)?\s*원/i.test(txt))policy-=28;if(sales.testimonials&&sales.testimonials.length)policy-=22;
 var depth=atlasClamp(45+Math.min(35,body/800)+(ch.filter(function(c){return c.actionItems&&c.actionItems.length>=3;}).length*3));
 var total=atlasClamp((completeness+readability+salesScore+policy+depth)/5);
 var notes=[];if(body<18000)notes.push('본문 분량이 짧습니다. 핵심 챕터를 더 구체화하면 만족도가 높아집니다.');if(ch.length<6)notes.push('목차가 단순합니다. 독자가 따라가기 쉬운 단계형 구성을 권장합니다.');if(salesScore<85)notes.push('후킹·FAQ·구매 판단 정보 중 일부가 약합니다. 판매자료만 다시 생성할 수 있습니다.');if(policy<100)notes.push('과장 또는 증빙이 필요한 표현이 감지됐습니다. 정책 정리를 실행하세요.');if(!notes.length)notes.push('구성·가독성·판매자료가 균형 있게 준비됐습니다. 최종 문구만 직접 확인하세요.');
 return {total:total,completeness:completeness,readability:readability,sales:salesScore,policy:atlasClamp(policy),depth:depth,notes:notes};
}
function atlasQualityHTML(e,compact){var q=atlasQualityScores(e);return '<div class="atlas-final-tools"><div class="aft-head"><div><div class="aft-kicker">ATLAS AI QUALITY COACH</div><div class="aft-title">전자책 완성도 점검</div></div><div class="aft-score">'+q.total+'</div></div><div class="aft-grid"><div class="aft-metric"><b>'+q.completeness+'</b><span>구성 완성도</span></div><div class="aft-metric"><b>'+q.readability+'</b><span>가독성</span></div><div class="aft-metric"><b>'+q.sales+'</b><span>판매 설득력</span></div><div class="aft-metric"><b>'+q.policy+'</b><span>정책 안전도</span></div></div><div class="aft-note">🤖 '+q.notes.join('<br>• ')+'</div><div class="aft-actions"><button class="aft-btn primary" onclick="openAtlasPartialModal()">🪄 필요한 부분만 수정</button><button class="aft-btn" onclick="atlasApplySafeClaims()">🛡️ 위험 표현 정리</button><button class="aft-btn" onclick="openTitleStudio(true)">✨ 제목 다시 추천</button></div></div>';}
function renderAtlasQuality(){var a=document.getElementById('atlas-quality-body'),b=document.getElementById('atlas-sales-quality-body');if(a)a.innerHTML=APP.ebook?atlasQualityHTML(APP.ebook,false):'';if(b)b.innerHTML=APP.ebook?atlasQualityHTML(APP.ebook,true):'';}
function atlasApplySafeClaims(){if(!APP.ebook)return;APP.ebook=sanitizeKmongSalesClaims(APP.ebook);renderCvEbook(APP.ebook);renderKmongListing(APP.ebook);renderKmongThumbnails(APP.ebook);renderAtlasQuality();atlasSaveDraft(false);showToast('success','위험 표현을 안전하게 정리했습니다.');}
function openAtlasPartialModal(){if(!APP.ebook){showToast('error','전자책을 먼저 생성해주세요.');return;}var opts=(APP.ebook.chapters||[]).map(function(c,i){return '<option value="chapter:'+i+'">'+(i+1)+'장 · '+x(c.title||'챕터')+'</option>';}).join('');var bg=document.createElement('div');bg.className='atlas-modal-bg';bg.id='atlas-partial-modal';bg.innerHTML='<div class="atlas-modal"><h3>필요한 부분만 다시 만들기</h3><p>완성된 전자책은 유지하고 선택한 부분만 다시 생성합니다. 처음부터 15분을 다시 기다릴 필요가 없습니다.</p><div class="atlas-form-row"><label>수정할 부분</label><select id="atlas-partial-type"><option value="sales">판매자료·후킹·FAQ</option><option value="intro">서론</option><option value="conclusion">결론</option><option value="appendices">부록 전체</option>'+opts+'</select></div><div class="atlas-form-row"><label>수정 방향</label><textarea id="atlas-partial-direction" placeholder="예: 초보자가 이해하기 쉽게, 사례를 더 구체적으로, 과장 없이 후킹 강화"></textarea></div><div class="atlas-modal-actions"><button class="aft-btn" onclick="document.getElementById(\'atlas-partial-modal\').remove()">취소</button><button class="aft-btn primary" id="atlas-partial-run" onclick="runAtlasPartialRegeneration()">선택 부분 다시 생성</button></div></div>';document.body.appendChild(bg);}
async function runAtlasPartialRegeneration(){var type=document.getElementById('atlas-partial-type').value,dir=document.getElementById('atlas-partial-direction').value.trim(),key=getApiKey(),btn=document.getElementById('atlas-partial-run');if(!key||key.length<10){showToast('error','API 키를 먼저 설정해주세요.');return;}btn.disabled=true;btn.textContent='생성 중...';var target='',schema='';if(type==='sales'){target=JSON.stringify(APP.ebook.sales||{});schema='sales 객체만 반환: {"hook":"","subhook":"","pains":[],"solution":"","learnings":[],"benefits":[],"before":[],"after":[],"testimonials":[],"faqs":[{"q":"","a":""}],"finalPush":""}';}else if(type.indexOf('chapter:')===0){var idx=Number(type.split(':')[1]);target=JSON.stringify(APP.ebook.chapters[idx]||{});schema='챕터 객체만 반환: {"number":'+(idx+1)+',"title":"","content":"","actionBox":"","keyPoints":[],"actionItems":[]}';}else if(type==='appendices'){target=JSON.stringify(APP.ebook.appendices||[]);schema='부록 배열만 반환: [{"title":"","content":""}]';}else{target=JSON.stringify(APP.ebook[type]||'');schema='문자열 값 하나를 {"content":"..."} 형태로 반환';}
 var prompt='당신은 한국어 전자책 전문 편집자입니다. 전체 전자책의 제목과 방향은 유지하고 선택한 부분만 고쳐 쓰세요. 입력에 없는 경험·실적·통계를 만들지 마세요. 구체적인 수익 금액, 보장, 100%, 무조건 표현을 쓰지 마세요. 수정 방향: '+(dir||'가독성과 실전성을 높이고 후킹을 강화')+'\n\n전자책 요약: '+JSON.stringify({title:APP.ebook.title,subtitle:APP.ebook.subtitle,description:APP.ebook.description,targetReader:APP.ebook.targetReader})+'\n\n현재 선택 부분: '+target+'\n\n'+schema+'\n유효한 JSON만 반환하세요.';
 try{var resp=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body:JSON.stringify({model:'claude-sonnet-4-6',max_tokens:type.indexOf('chapter:')===0?9000:5000,system:'유효한 JSON 하나만 반환하세요.',messages:[{role:'user',content:[{type:'text',text:prompt}]}]})});var data=await resp.json();if(!resp.ok)throw new Error(data.error&&data.error.message||'부분 생성 실패');var raw=(data.content||[]).filter(function(z){return z.type==='text';}).map(function(z){return z.text;}).join('').replace(/```json|```/g,'').trim();var obj=JSON.parse(raw.substring(raw.indexOf(type==='appendices'?'[':'{'),raw.lastIndexOf(type==='appendices'?']':'}')+1));if(type==='sales')APP.ebook.sales=obj;else if(type.indexOf('chapter:')===0)APP.ebook.chapters[Number(type.split(':')[1])]=obj;else if(type==='appendices')APP.ebook.appendices=obj;else APP.ebook[type]=obj.content||'';APP.ebook=sanitizeKmongSalesClaims(APP.ebook);renderCvEbook(APP.ebook);renderAtlasQuality();atlasSaveDraft(false);var m=document.getElementById('atlas-partial-modal');if(m)m.remove();showToast('success','선택한 부분만 새로 만들었습니다.');}catch(e){showToast('error','부분 수정 실패: '+e.message,5000);}finally{btn.disabled=false;btn.textContent='선택 부분 다시 생성';}}
// Hook existing renders without changing core code
(function(){var oldRender=window.renderCvEbook;window.renderCvEbook=function(e){oldRender(e);setTimeout(renderAtlasQuality,0);};var oldSales=window.renderCvSalesPage;window.renderCvSalesPage=function(e,t){oldSales(e,t);setTimeout(renderAtlasQuality,0);};})();
